### ISSUE TITLE
CloudAuthorizer::getValue returns incorrect string

### ISSUE THREAD

**Issue by NexusDeveloper** [SerjPopov/cloud-mail-ru-php#11]
Указанный в заголовке метод возвращает неверный результат. 

В возвращаемый результат метода попадают данные "по соседству". 
Например при поиске строки 'csrf' в ответе функция возвращает  `<token>"},"user` Вместо `<token>`.
Для 'x-page-id': `<id>","ON_PREMISE` вместо `<id>`
Для 'build': `<build>","PROMO_TOP_BANNER` вместо `<build>`.

Это приводит к тому, что [сервер облака возвращает 403 ошибку](https://github.com/SerjPopov/cloud-mail-ru-php/issues/9).

Для решения проблемы стоит заменить указанный метод следующим:
```php
private static function getValue(string $str, string $find)
{
    $start = strpos($str, '"' . $find . '"');
    if ($start > 0) {
        $end = strpos($str, PHP_EOL, $start);
        $strValue = substr($str, $start, $end - $start);
        $valuerArr = explode(':', $strValue);
        $value = trim($valuerArr[1] ?? '', '"');
        $valuerArr = explode('"', $value);
        $value = $valuerArr[0] ?? '';
        $value = trim($value);
        $value = trim($value, ',"');
        return $value;
    } else {
        return '';
    }
}
```

Прошу прощения, что без pull request'а.

**Comment by Heivor** [comment]
Заменил метод, но что-то всё ровно 403 ошибка

**Comment by SerjPopov** [comment]
Обновил библиотеку. Данную проблему тоже устранил.
