### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mahirozdin** [SerjPopov/cloud-mail-ru-php#3]
php file not working and always gives error

here is my code
`<?php

require 'cloudmailru.php';
$cloud = new CloudMailRu('xxxxxx@mail.ru','xxxxx');
if ($cloud->login()) {
    
    $file = dirname(__FILE__).'\test.txt';
	echo $file;
    $file_cloud = 'test.txt';
    
  //  $url = $cloud->loadFileAhdPublish($file, $file_cloud);
    
    if ($url == "error") {
        echo 'ERROR '.$url;
    } else {
        
		echo $url;
    }
    
} else {
    echo 'Giriş Başarısız';
}

unset($cloud);
?>`

**Comment by idiked** [comment]
try to use CURLFile object in loadFile_to_cloud():
`$post_data = array("file" => new CURLFile($file_name, null, basename($file_name)));`
instead of:
`$post_data = array("file" => "@" . $file_name);`

**Comment by zullusa** [comment]
Try without @mail.ru
`$cloud = new CloudMailRu('xxxxxx','xxxxx');`

Athor hasn't considered many MAIL.RU hosts (like bk.ru list.ru). He has hardcoded only mail.ru in source.

**Comment by polakiv** [comment]
не работает , эх....
видимо точка входа для авторизации поменялась

**Comment by vaajnur** [comment]
не авторизуется

**Comment by SerjPopov** [comment]
Исправлено в версии 2.0.0
